name: Python SDK Test workflow

on:
  push:
    branches:
      - main # Reemplaza con la rama de tu elección

jobs:
  comment-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: Pytest Appium Repo ${{ matrix.python }} - ${{ matrix.os }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: run tests in parallel on android
        run: |
          cd android
          browserstack-sdk pytest -s bstack_sample.py

      - name: run local tests in parallel on android
        run: |
          cd android
          browserstack-sdk pytest -s bstack_sample_local.py --browserstack.app "./LocalSample.apk"

      - name: run tests in parallel on ios
        run: |
          cd ios
          browserstack-sdk pytest -s bstack_sample.py

      - name: run local tests in parallel on ios
        run: |
          cd ios
          browserstack-sdk pytest -s bstack_sample_local.py --browserstack.app "./LocalSample.ipa"
