# This workflow targets Appium execution for Android only

name: Python SDK Test workflow on workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "The full commit id to build"
        required: true

jobs:
  comment-run:
    runs-on: ubuntu-latest
    name: Pytest Appium Repo - Android Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Puedes ajustar a la versión que prefieras

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: run tests in parallel on android
        run: |
          cd android
          browserstack-sdk pytest -s bstack_sample.py
